path: {
  data_dir: "./dataset/en-ko",
  corpus_name: "aihub_ko.txt",
  output_path: "./tokenizers/morpheme_aware_BPE",
}

tokenizer: {
  vocab_languages: "ko",
  vocab_size: [2000, 4000, 8000, 16000, 32000, 64000, 128000],
  vocab_type: "morpheme_aware_BPE",
  max_sentence_length: 999999,
  args:{
    num_threads: 32,
  },
}