path: {
  data_dir: "../../../simul-tokenization/dataset/en-ko/",
  corpus_name: "aihub_ko.txt"
}

tokenizer: {
  prefix: "ko_vocab",
  vocab_size: 16000,
  vocab_type: "bpe",
  args:{
    num_threads: 32,
  },
}